apiVersion: v1 
kind: Service 
metadata:
  name: mysql-headless
  namespace: roboshop 
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
     component: mysql
     project: roboshop
     tier: database